### PR TITLE
Fix types handling

### PR DESCRIPTION
**Pull request by filipelautert**
Restore previous behavior and handle diff when the size/length of a field changes.

### CODE REVIEW

**Comment by javaboy79** [comment]
@filipelautert My test produces an NPE
`Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "liquibase.structure.core.DataType.getColumnSize()" is null
        at liquibase.ext.hibernate.diff.ChangedColumnChangeGenerator.handleSizeChange(ChangedColumnChangeGenerator.java:47)
        at liquibase.ext.hibernate.diff.ChangedColumnChangeGenerator.handleTypeDifferences(ChangedColumnChangeGenerator.java:33)
        at liquibase.diff.output.changelog.core.ChangedColumnChangeGenerator.fixChanged(ChangedColumnChangeGenerator.java:66)
        at liquibase.diff.output.changelog.ChangeGeneratorChain.fixChanged(ChangeGeneratorChain.java:137)
        at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixChanged(ChangeGeneratorFactory.java:117)
        at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:282)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:230)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:149)
        ... 38 more`

**Comment by filipelautert** [comment]
I should have tested with fields that don't have sizes. Well, fixed now! Can you give it another try @javaboy79 ? Thank you!

**Comment by javaboy79** [comment]
This is mostly working now.  However, I am still ending up with items in my diff that should not be there.  `timestamp` types are always listed for modify.  I tried applying the change, and still, they are listed again on the next diff.  So, clearly, something is still wrong with the diff.

All other reported types are now cleared from the diff.

**Comment by javaboy79** [comment]
@filipelautert I feel like you were making good progress on this.  Do you have any feedback or fix for my last comment?

**Comment by filipelautert** [comment]
Hello @javaboy79 ! I think there is no other way but creating a list of type exclusions for the size checks.
In the end this is good, as before it was excluding everything, but now we can choose what to exclude.
I went ahead and added timestamp. If there is anything else let me know and I can add to the list. I want to finish this in time for the next release.

**Comment by javaboy79** [comment]
Another NPE:
`Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "liquibase.structure.core.DataType.getColumnSize()" is null
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:207)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:96)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:90)
        at liquibase.command.core.InternalDiffChangelogCommandStep.run(InternalDiffChangelogCommandStep.java:63)
        at liquibase.command.CommandScope.execute(CommandScope.java:172)
        ... 29 more
Caused by: java.lang.RuntimeException: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "liquibase.structure.core.DataType.getColumnSize()" is null
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:190)
        at liquibase.Scope.lambda$child$0(Scope.java:180)
        at liquibase.Scope.child(Scope.java:189)
        at liquibase.Scope.child(Scope.java:179)
        at liquibase.Scope.child(Scope.java:158)
        at liquibase.diff.output.changelog.DiffToChangeLog.print(DiffToChangeLog.java:143)
        ... 33 more
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "liquibase.structure.core.DataType.getColumnSize()" is null
        at liquibase.ext.hibernate.diff.ChangedColumnChangeGenerator.handleSizeChange(ChangedColumnChangeGenerator.java:47)
        at liquibase.ext.hibernate.diff.ChangedColumnChangeGenerator.handleTypeDifferences(ChangedColumnChangeGenerator.java:33)
        at liquibase.diff.output.changelog.core.ChangedColumnChangeGenerator.fixChanged(ChangedColumnChangeGenerator.java:66)
        at liquibase.diff.output.changelog.ChangeGeneratorChain.fixChanged(ChangeGeneratorChain.java:137)
        at liquibase.diff.output.changelog.ChangeGeneratorFactory.fixChanged(ChangeGeneratorFactory.java:117)
        at liquibase.diff.output.changelog.DiffToChangeLog.generateChangeSets(DiffToChangeLog.java:282)
        at liquibase.diff.output.changelog.DiffToChangeLog.printNew(DiffToChangeLog.java:230)
        at liquibase.diff.output.changelog.DiffToChangeLog$1.run(DiffToChangeLog.java:149)`

**Comment by filipelautert** [comment]
Hm.. this time the problem was down there on liquibase core. Seems I passed something with null that could not be handled .
I believe I fixed it, here we go again...

**Comment by filipelautert** [comment]
@javaboy79 When you have some time, it's ready for another run.

**Comment by javaboy79** [comment]
Yes, I'm out of town this week.  I should be able to give it another run on
Monday.

**Comment by filipelautert** [comment]
Hello @javaboy79 - I'm merging this as is for 4.21.0 that is going to be out today. If the problem persists let's continue from here 👍

**Comment by javaboy79** [comment]
@filipelautert Thank you for your efforts here!  This is looking really good.  Today I was able to pull 4.21.1 into my project and the diff produced actually found and correctly reported a discrepancy on one of my varchar lengths.  This is great!  However, as far as I can see, there is one problem left...

The diff is also reporting false positives on my unique indexes.  Mind you, this is only happening for **unique** indexes.  Other indexes seem fine.

e.g. (names obfuscated)
`@Table(
    indexes = {
      @Index(name = "my_id_index", columnList = "id", unique = true),
    })`

Even though the db already shows this as unique, the diff produces the following:
`<changeSet author="user (generated)" id="1681760762251-3">
        <dropUniqueConstraint constraintName="my_id_index" tableName="xxx"/>
    </changeSet>`

**Comment by javaboy79** [comment]
@filipelautert This is also happening on unique constraints that were previously generated by the column annotation:
`@Column(unique = true)`
These are similarly being reported as a drop by the diff.

**Comment by filipelautert** [comment]
I'll create another PR until tomorrow and will tag you there.

**Comment by javaboy79** [comment]
@filipelautert Looks like it has already been reported.  #479

**Pull request merged**
