### PR TITLE
When set the default schema/catalog name is used instead of the default HIBERNATE one

### PR DESCRIPTION
**Pull request by tuxBurner**
Hi,

  i ran into the problem when i set the following options in my pom.xml

`
<referenceDefaultSchemaName>main</referenceDefaultSchemaName>              <diffIncludeSchema>true</diffIncludeSchema>
`

i always got **HIBERNATE.** in front of my changes  but i expect it to be **main.**

This fixes it for me.

### CODE REVIEW

**Comment by r2datical** [comment]
@nvoxland Can you review please? Looks straight forward to me but wanted to make sure.

Thank you, @tuxBurner !!!

**Comment by tuxBurner** [comment]
Sure @r2datical :)

**Comment by r2liquibase** [comment]
@nvoxland What do you think?

**Comment by tuxBurner** [comment]
Hi @r2liquibase,

 any reason why you closed the PR without merging it ? 

Greetings tuxBurner

**Pull request closed without merging**
