### PR TITLE
use hibernate.temp.use_jdbc_metadata_defaults=false everywhere like for HibernateClassic

### PR DESCRIPTION
**Pull request by jonenst**
see https://github.com/liquibase/liquibase-hibernate/commit/4926f5208c44b4e71912a397ecd629ee594e4a7d#r130325454

Related issues: https://github.com/liquibase/liquibase-hibernate/issues/431 and variants : https://github.com/liquibase/liquibase-hibernate/issues/482 https://github.com/liquibase/liquibase-hibernate/issues/481 https://github.com/liquibase/liquibase-hibernate/issues/482 https://github.com/liquibase/liquibase-hibernate/issues/381#issuecomment-1517676580

### CODE REVIEW

**Comment by filipelautert** [comment]
@jonenst nice! Your idea is to have it fixed on hibernate5 or 6 first?

**Comment by jonenst** [comment]
hi @filipelautert , for both ? the property is the same 
https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#configurations-internal
https://docs.jboss.org/hibernate/orm/5.6/userguide/html_single/Hibernate_User_Guide.html#configurations-internal

**Review by filipelautert — APPROVED** [review]

**Comment by filipelautert** [comment]
So let's start with 6 and next release backport it to 5. Thanks @jonenst !

**Comment by jonenst** [comment]
Hi @filipelautert , FYI I had a discussion with the hibernate maintainers at https://github.com/hibernate/hibernate-orm/pull/7182#issuecomment-1752706362 regarding the use of `use_jdbc_metadata_defaults=false`. Unfortunately It looks like it will be removed soon so this will need to be revisited. From what I understand, they do plan to support its features, just with more fine grained configuration. However they wanted to know more about the use cases of liquibase-hibernate and their technical implications. I think it would be a good idea to talk to them before the parameter is removed.

>  What are they trying to accomplish by setting `use_jdbc_metadata_defaults=false`? Can they reach out (on Zulip would be ideal or a "Proposal" issue in our Jira)

**Comment by filipelautert** [comment]
Thanks for talking to upstream hibernate team @jonenst . So I'll revert this pr for now then we can get 4.25.0 out without that, but let's keep on working with hibernate team to find out the best approach for that.

**Pull request merged**
