### PR TITLE
Removes customized column generator allowing liquibase default column handler to be executed

### LINKED ISSUE #48: data type modification not tracked
Changing an enum type to string is not tracked in change sets.

E.g. changing chartType from (default) int ....

```
@Entity
public class Chart {
    public enum ChartType {
            AREA, AREASPLINE, BAR, COLUMN, LINE, PIE, SCATTER, SPLINE
    }

    @Column(nullable = false, length = 50)
    private ChartType chartType;
}
```

to string

```
@Entity
public class Chart {
    public enum ChartType {
            AREA, AREASPLINE, BAR, COLUMN, LINE, PIE, SCATTER, SPLINE
    }

    @Column(nullable = false, length = 50)
    @Enumerated(EnumType.STRING)
    private ChartType chartType;
}
```

"change set" should be

```
<modifyDataType
tableName="chart" columnName="chart_type" newDataType="VARCHAR(50)" />
```

but is empty

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-483) by [Unito](https://www.unito.io/learn-more)

### LINKED ISSUE #163: Changelog does not generate on changing column size in annotation on Hibernate 5
Example - @Column(length = 20) in system, now only change the length to any other number, and try generating the changelog difference. Changelog does not show the changed column size.

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-468) by [Unito](https://www.unito.io/learn-more)

### PR DESCRIPTION
**Pull request by filipelautert**
liquibase-hibernate class ChangedColumnChangeGenerator was overring the default liquibase class due to old restrictions on liquibase/hibernate integration. Since both improved over the years, this class can be removed allowing liquibase default behaviour to happen.

Fixes #163 
Fixes #48

### CODE REVIEW

**Review by suryaaki2 — APPROVED** [review]

**Review by XDelphiGrl — APPROVED** [review]
PR removes Hibernate override of Liquibase default `diff` behavior, fixing a bug in snapshotting changed column types and sizes.
* Functional and test harness executions are passing.
* No additional testing required.

APPROVED

**Comment by praveen0821** [comment]
Hi team,

We have configured Liquibase with our spring boot project which runs/builds on gradle.

As per mentioned above the data type changes should work, but the data type modify changes for a column is not reflecting in the changelog set, it says no effected changes.

Mentioned above as 
Alternately, you can use the [Liquibase SDK Maven Plugin](https://mvnrepository.com/artifact/org.liquibase.ext/liquibase-sdk-maven-plugin).

Could you please explain us how this can be used for gradle to make it work.

Using plugin and dependencies of liquibase are as follows:
Plugin: org.liquibase.gradle, version: 2.1.1
Hibernate: liquibaseHibernate5, version: 4.19.0

Please let me know if you need any details.

**Comment by javaboy79** [comment]
This change has completely broken my diffChangelog commands.  Every time I run the diff, it now produces an entry like so for nearly all columns in my db (postgres).
`<modifyDataType tableName="tablename" columnName="pkid" newDataType="bytea"/>`

I have noted that columns don't seem to be recognized properly.  For instance, the entry above is for a UUID type.  The db currently is uuid, java type is UUID.  However, it generates a statement to modify to bytea.

I doubt this is configuration related, as it has been working properly in my project through many changes, right up until v4.19.1

Please advise.  Is this a bug?

**Comment by filipelautert** [comment]
Hello @javaboy79 - it is happening only for some types of columns like UUID or for all of them? Liquibase column change generator should be able to handle it, but maybe we need to add some conversion for some types - or even adapt something on liquibase core.

**Comment by filipelautert** [comment]
@praveen0821 oh I see, it was only merged for Hibernate 6. I'll create a PR to include it on next release and tag you there.

**Comment by javaboy79** [comment]
I am using hibernate6 version.  It seems to be happening on several types.  I do not see a clear reason.  I did note that I could get the `uuid`->`bytea` mappings to stop by providing my own dialect (somewhat like [PostgreSQL10Dialect](https://github.com/hibernate/hibernate-orm/blob/main/hibernate-core/src/main/java/org/hibernate/dialect/PostgreSQL10Dialect.java)).  

I suspect dialect version config is part of the issue.  With that said, there are several modifications that are still unexpected, like `boolean`.  They are always in my diff.

**Comment by javaboy79** [comment]
I verified and every single column is now getting flagged for `modifyDataType` on a diff.  With the aforementioned dialect config, it removes uuids from the list.  Otherwise, all columns are getting flagged.  

This includes: `boolean`, `integer`, `smallint`, `bigint`, `varchar`, `timestamp`.  

The only types not in the diff are `uuid` (but only with the custom config, otherwise these go to `bytea`) and `oid` (which is postgresql text type)

Any suggestions?

**Comment by filipelautert** [comment]
Hello @javaboy79 - PR https://github.com/liquibase/liquibase-hibernate/pull/467 rollbacks previous behavior and just adds verification to the column sizes, ignoring the types as before.
Would you mind confirming if it fixes the issues introduced by latest versions?

**Pull request merged**
