### PR TITLE
bump Hibernate to 5.4.25.Final

### PR DESCRIPTION
**Pull request by r2liquibase**
┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1043) by [Unito](https://www.unito.io/learn-more)

### CODE REVIEW

**Comment by nmck257** [comment]
@r2liquibase - I see the latest release cut still has hibernate 5.4.4. Do we have any specific blockers with upgrading the hibernate version?

**Comment by r2liquibase** [comment]
ARGH! Dependabot did me wrong! https://github.com/liquibase/liquibase-hibernate/pull/287/

My apologies. Imma get this fixed now on that PR.

**Comment by nmck257** [comment]
Ha!

Yeah, I'm no expert on dependabot -- but I appreciate the manual intervention to get it updated :)

**Comment by r2liquibase** [comment]
Updated, waiting on a build and then Imma push this out for 4.3.0.1. Thanks a ton for the heads up! I would have totally missed that without you!

**Pull request closed without merging**
